server:
  port: 8080
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for

spring:
  application:
    name: incheon_mate-backend

  mongodb:
    uri: ${MONGO_URI}

  data:
    mongodb:
      auto-index-creation: false

  redis:
    host: ${REDIS_HOST:redis}
    port: 6379





google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${GOOGLE_FRONTEND_REDIRECT_URI}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_FRONTEND_REDIRECT_URI}
  api:
    key: ${KAKAO_KEY}

jwt:
  secret: ${JWT_SECRET}

#AI 서버와의 EC2간 통신을 위한 URL 추가
app:
  ai-server:
    url: ${AI_SERVER_URL}
  naegift:
    url: ${NAEGIFT_REWARD_URL}

#운영환경에서는 swagger 꺼두기
springdoc:
  api-docs:
    enabled: false
    path: /v3/api-docs
  swagger-ui:
    enabled: false
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

#로그 레벨 INFO로 조정
logging:
  level:
    root: info
    com.example.IncheonMate: info
