server:
  port: 8080
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for

spring:
  application:
    name: incheon_mate-backend


  #  Spring Boot 4.x Mongo 설정 (deprecated 아님)
  mongodb:
    uri: mongodb://${DB_HOST:localhost}:27017/incheon_mate_db
    #uri: mongodb://${DB_HOST:mongodb}:27017/incheon_mate_db



  data:
    mongodb:
      auto-index-creation: true
    #  Redis는 spring.data.redis 아래가 정석
    redis:
      #host: ${REDIS_HOST:redis}
      host: ${REDIS_HOST:localhost}
      port: 6379



google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: "https://2025-capstone-design-fe.vercel.app/auth/google/callback"

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: "https://2025-capstone-design-fe.vercel.app/auth/kakao/callback"
  api:
    key: ${KAKAO_KEY}


jwt:
  secret: ${JWT_SECRET}

#AI 서버와의 EC2간 통신을 위한 URL 추가
app:
  ai-server:
    url: ${AI_SERVER_URL:http://localhost:8000}
  naegift:
    url: ${NAEGIFT_REWARD_URL}




springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

#com.example.IncheonMate만 로깅 레벨을 Debug로 조정
logging:
  level:
    root: INFO
    com.example.IncheonMate: DEBUG



